### PR TITLE
Multiple fixes and performance improvements with multiprocessing + multithreading

### PR DESCRIPTION
**Pull request by maaaaz**
Fixes for :
* https://github.com/atenreiro/opensquat/issues/83
* https://github.com/atenreiro/opensquat/issues/84

### CODE REVIEW

**Comment by maaaaz** [comment]
This commit also contain performance improvements, by multiprocessing domain squatting check (CPU bound), and multithreading port scans (IO bound).

As a matter of example, for a domain file containing 40000 entries, and a keyword file of 480 entries:
* before this commit, it took 40 minutes for domain squatting check
* now, it only takes 10 min

For the port scan check, it also drastically reduces operation duration.

**Comment by atenreiro** [comment]
Hey @maaaaz 

Awesome updates :-)

Give a few days to review the pull request.

Thanks for your contributions!

Andre

**Comment by atenreiro** [comment]
@maaaaz I will be making a promotional post on Linkedin and Twitter for the major features released today. Let me know if you want to be tagged for your contribution and, if yes, to which social media profile. Thanks for your great contribution :-)

**Comment by maaaaz** [comment]
Thanks André, if you want, you can just include my Github handle.

**Comment by atenreiro** [comment]
> Thanks André, if you want, you can just include my Github handle.

awesome! thanks

**Pull request merged**
